### ISSUE TITLE
Can map options be set on the "googleMaps" object?

### ISSUE THREAD

**Issue by tylerhartwig** [fable-compiler/Fable.ReactGoogleMaps#12]
Hi, looking for an example on how to use the `MapOptions` object of the library. An example would be much appreciated. Thanks!

**Comment by nojaf** [comment]
I'm guessing just create an anonymous record with your options and pass it as [Options](https://github.com/fable-compiler/Fable.ReactGoogleMaps/blob/master/src/Fable.ReactGoogleMaps.fs#L99) obj.

**Comment by tylerhartwig** [comment]
that seems to be the case, thanks @nojaf
