### ISSUE TITLE
LatLngBounds missing

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable.ReactGoogleMaps#2]
@nojaf any ideas?

![image](https://user-images.githubusercontent.com/57396/56642781-81b8ee80-6678-11e9-8754-84f0f8801e6b.png)

**Comment by forki** [comment]
open Fable.Import.GoogleMaps doesn't compile as well

**Comment by MangelMaxime** [comment]
Are you sure you don't need to upgrade `Fable.Import.GoogleMaps` to Fable.Core v3.0. And `Fable.ReactGoogleMaps` too?

Personally, for `Fable.ReactLeaflet`, I upgraded (in order):

- Fable.GeoJson
- Fable.Leaflet
- Fable.ReactLeaflet

PS: The new convention started by Alfonso is now to remove at least `Import` from `Fable.Import.GoogleMaps` namespace. You could go further and do like other package and just use `GoogleMaps` as the namespace/module so it's directly accessible to the user.

**Comment by alfonsogarciacaro** [comment]
#3

**Comment by forki** [comment]
I was able to release 0.8.1. Thank you!

**Comment by MangelMaxime** [comment]
> I was able to release 0.8.1. Thank you!

Yes... but you internalized `GoogleMaps` binding in this package instead of using it as a dependency and fixing it the original library...

**Comment by forki** [comment]
yeah this is an intermediate step. I'm open to more PRs

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/56897457-e87e4380-6a8e-11e9-893e-83519819a348.png)

how do I crate a LatLngLiteral?

**Comment by MangelMaxime** [comment]
Not all the library has been internalized so the [helpers](https://github.com/fable-compiler/fable-import/blob/master/GoogleMaps/Fable.Helper.GoogleMaps.fs) are missing.

As said before, someone using `Fable.ReactGoogleMaps` should take ownership of `Fable.GoogleMaps` too port it to Fable.Core v3.

Revert the internalization of the binding in `Fable.ReactGoogleMaps` and then all will be like before.
