### ISSUE TITLE
Is readme up to date?

### ISSUE THREAD

**Issue by isaacabraham** [fable-compiler/Fable.ReactGoogleMaps#5]
The latest version of the Fable.ReactGoogleMaps project (0.8.2) seems to have a totally different API to the "old" version that's referenced in the readme. Have I done something wrong or do the docs just need updating?

**Comment by nojaf** [comment]
Hmm, maybe some namespaces changed.
What are you trying?

**Comment by isaacabraham** [comment]
It's no longer `Fable.Helpers.ReactGoogleMaps` but just `Fable.ReactGoogleMaps`.

**Comment by isaacabraham** [comment]
Thanks :-)
